AllCops:

  TargetRubyVersion: 2.5

  Exclude:
  - 'Vagrantfile'
  

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
