AllCops:

  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
  - 'Vagrantfile'
  

Layout:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 7

Style/SafeNavigation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
